language: node_js
node_js:
  - "8"
  - "9"
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - jest --config test/unit/jest.conf.js --coverage --coverageReporters=text-lcov | coveralls
